export const LIGHT_COLORS = {
  "--color-text": "var(--cool-grey-90)",
  "--color-text-secondary": "var(--cool-grey-80)",
  "--color-text-third": "var(--cool-grey-70)",
  "--color-line": "var(--cool-grey-30)",
  "--color-background": "hsl(210deg, 20%, 98%)",
  "--teal-primary": "var(--teal-70)",
  "--teal-hover": "var(--teal-80)",
  "--teal-background": "var(--teal-20)",
  "--button-background": "var(--cool-grey-5)",
  "--button-hover": "var(--cool-grey-10)",
  "--button-hover-text": "var(--rich-black)",
  "--gradient": "linear-gradient(to right, var(--teal-70), transparent)",
  // '--teal-secondary': 'hsl(345deg 100% 50%)',
};

export const DARK_COLORS = {
  "--color-text": "var(--cool-grey-5)",
  "--color-text-secondary": "var(--cool-grey-10)",
  "--color-text-third": "var(--cool-grey-20)",
  "--color-line": "var(--neutral-grey-60)",
  "--color-background": "hsl(230deg, 20%, 8%)",
  "--teal-primary": "var(--teal-10)",
  "--teal-background": "var(--teal-80)",
  "--teal-hover": "var(--teal-20)",
  "--button-background": "black",
  "--button-hover": "var(--cool-grey-10)",
  "--button-hover-text": "var(--cool-grey-90)",
  "--gradient": "linear-gradient(to right, var(--teal-70), transparent)",
  // '--teal-secondary': 'hsl(210deg 100% 70%)',
};
